# Site-wide generic info (overridable per-page)
title: seanmcknight.github.io
description: The personal site and résumé of Sean McKnight
author: Sean McKnight
theme-color: "#0a74ff"

# Site-wide hardcoded (non-overridable by pages)
made-in: Colorado
birthday: '1992-08-06 00:08:00 -0600'

# Site-wide social info
email: sionemcknight@gmail.com
twitter: "@seankmcknight
github:
  user: sionemcknight
  repo: seanmcknight.github.io
gravatar: ae28be3e678171c14d6bc4b94e90672e # Gravatar md5 hash

# Settings
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from
