# Site-wide generic info (overridable per-page)
title: ryanleesipes.me
description: The personal site and résumé of Ryan Sipes
author: Ryan Lee Sipes
theme-color: "#0a84ff"

# Site-wide hardcoded (non-overridable by pages)
made-in: Colorado
birthday: '1990-03-25 00:08:00 -0600'

# Site-wide social info
email: ryan@sipes.us
twitter: "@ryanleesipes"
github:
  user: ryanleesipes
  repo: ryanleesipes.github.io
gravatar: 07d01f23cef0e26326276a8d519586fe # Gravatar md5 hash

# Settings
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from
