# Site-wide generic info (overridable per-page)
title: CassidyJames.com
description: The personal site and résumé of Cassidy James Blaede
author: Cassidy James Blaede
theme-color: "#525"

# Site-wide hardcoded (non-overridable by pages)
made-in: Colorado

# Site-wide social info
email: c@ssidyjam.es
twitter: "@CassidyJames"
github:
  user: cassidyjames
  repo: cassidyjames.com
square: "$cassidyjames"
google-plus: "+CassidyJames"
medium: "@cassidyjames"
instagram: cassidy.james.blaede
gravatar: 41275ecc8271aca852ce2c0ff72d2610 # Gravatar md5 hash

# Settings
permalink: pretty
